name: 'Hello world' #*
description: 'says hello world' #*
inputs:
  who-to-greet:  # id of input *
    description: 'Who to greet' #*
    required: true #*
    default: 'World'
outputs:
  time: # id of output #*
    description: 'The time we greeted you' #*
runs: #* Configures the path to the action's code and the application used to execute the code.
  using: 'node12' #* application used to execute the code
  main: 'dist/index.js' #* file that contains the action code
